Put in a configure test for BSD

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3214,7 +3214,7 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "$as_me:$LINENO: checking whether struct stat has nanosecond resolution" >&5
 echo $ECHO_N "checking whether struct stat has nanosecond resolution... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
+         /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
@@ -3227,7 +3227,6 @@ struct stat st; st.st_mtim.tv_nsec=0;
   ;
   return 0;
 }
-
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3276,10 +3275,70 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+         cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/stat.h>
+int
+main ()
+{
+struct stat st; st.st_mtimespec.tv_nsec=0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_STAT_NSEC 1
+_ACEOF
+
+            cat >>confdefs.h <<\_ACEOF
+#define st_mtime_nsec st_mtimespec.tv_nsec
+_ACEOF
+
+            cat >>confdefs.h <<\_ACEOF
+#define st_atime_nsec st_atimespec.tv_nsec
+_ACEOF
+
+            cat >>confdefs.h <<\_ACEOF
+#define st_ctime_nsec st_ctimespec.tv_nsec
+_ACEOF
+
+            echo "$as_me:$LINENO: result: st_mtimespec is a struct timespec" >&5
+echo "${ECHO_T}st_mtimespec is a struct timespec" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-        { echo "$as_me:$LINENO: WARNING: file times will have a 1 second resolution" >&5
+            { echo "$as_me:$LINENO: WARNING: file times will have a 1 second resolution" >&5
 echo "$as_me: WARNING: file times will have a 1 second resolution" >&2;}
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
